ini_open("pelt_durability.ini")
global.pelt_slashing_modifier = ini_read_real("globals", "slashing", 0.75)
global.pelt_piercing_modifier = ini_read_real("globals", "piercing", 0)
global.pelt_blunt_modifier = ini_read_real("globals", "blunt", 0.05)
global.pelt_rending_modifier = ini_read_real("globals", "rending", 2)
global.pelt_fire_modifier = ini_read_real("globals", "fire", 3)
global.pelt_poison_modifier = ini_read_real("globals", "poison", 1.5)
global.pelt_frost_modifier = ini_read_real("globals", "frost", 0.75)
global.pelt_caustic_modifier = ini_read_real("globals", "caustic", 3)
global.pelt_shock_modifier = ini_read_real("globals", "shock", 1.5)
global.pelt_arcane_modifier = ini_read_real("globals", "arcane", 1.5)
global.pelt_psionic_modifier = ini_read_real("globals", "psionic", 0)
global.pelt_unholy_modifier = ini_read_real("globals", "unholy", 3)
global.pelt_sacred_modifier = ini_read_real("globals", "sacred", 0)
ini_close()